services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: linescorigami
      POSTGRES_USER: linescorigami-admin
      POSTGRES_PASSWORD: imagiro
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
